name: ec2 Deploy
on:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  call-ec2-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      work-dir: "environments/ec2"
      aws-region: "us-east-1"
    secrets:
      CI_ROLE: ${{ secrets.CI_ROLE }}
      SSH_KEY_GITHUB_ACTIONS: ${{ secrets.SSH_KEY_GITHUB_ACTIONS  }}